// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkke25cbYSvFmE9nfHA7wPaMfYIPMjToI',
    appId: '1:968331274025:web:b0f8824c8c2c15e48ab938',
    messagingSenderId: '968331274025',
    projectId: 'my-diary-8ec1e',
    authDomain: 'my-diary-8ec1e.firebaseapp.com',
    storageBucket: 'my-diary-8ec1e.firebasestorage.app',
    measurementId: 'G-49N7NLJBZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-PhPwIAJrYqbH6GfFsCVPMnDN6hDMNYw',
    appId: '1:968331274025:android:f045a0ee791b02588ab938',
    messagingSenderId: '968331274025',
    projectId: 'my-diary-8ec1e',
    storageBucket: 'my-diary-8ec1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjjHSsWmftPrANvULezP0cQWTFemOhdOs',
    appId: '1:968331274025:ios:499b0a8d42a65df98ab938',
    messagingSenderId: '968331274025',
    projectId: 'my-diary-8ec1e',
    storageBucket: 'my-diary-8ec1e.firebasestorage.app',
    iosBundleId: 'com.example.exambase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjjHSsWmftPrANvULezP0cQWTFemOhdOs',
    appId: '1:968331274025:ios:499b0a8d42a65df98ab938',
    messagingSenderId: '968331274025',
    projectId: 'my-diary-8ec1e',
    storageBucket: 'my-diary-8ec1e.firebasestorage.app',
    iosBundleId: 'com.example.exambase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkke25cbYSvFmE9nfHA7wPaMfYIPMjToI',
    appId: '1:968331274025:web:701d9e9af46404348ab938',
    messagingSenderId: '968331274025',
    projectId: 'my-diary-8ec1e',
    authDomain: 'my-diary-8ec1e.firebaseapp.com',
    storageBucket: 'my-diary-8ec1e.firebasestorage.app',
    measurementId: 'G-3ZNEEPKSNX',
  );
}
